In [26]:
#import necessory libraries
import pandas as pd

In [27]:
#load data
data=pd.read_csv(r"employe.csv")

In [28]:
data.columns

Index(['satisfactoryLevel', 'lastEvaluation', 'numberOfProjects',
       'avgMonthlyHours', 'timeSpent.company', 'workAccident', 'left',
       'promotionInLast5years', 'dept', 'salary'],
      dtype='object')

| Column Name | Description |
|-------------|-------------|
| satisfactoryLevel | Employee satisfaction score ranging from 0 to 1 indicating how satisfied the employee is with their job. |
| lastEvaluation | The employee’s last performance evaluation score ranging from 0 to 1. |
| numberOfProjects | Total number of projects the employee has worked on in the company. |
| avgMonthlyHours | Average number of hours the employee works per month. |
| timeSpent.company | Number of years the employee has spent working at the company. |
| workAccident | Indicates whether the employee had a work accident (1 = Yes, 0 = No). |
| left | Target variable indicating whether the employee left the company (1 = Left, 0 = Stayed). |
| promotionInLast5years | Indicates whether the employee received a promotion in the last 5 years (1 = Yes, 0 = No). |
| dept | Department in which the employee works (e.g., Sales, HR, IT). |
| salary | Salary level of the employee categorized as low, medium, or high. |

In [29]:
data.head()

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low

In [30]:
#statistical information
data.describe()

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [31]:
#descriptive information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfactoryLevel      14999 non-null  float64
 1   lastEvaluation         14999 non-null  float64
 2   numberOfProjects       14999 non-null  int64
 3   avgMonthlyHours        14999 non-null  int64
 4   timeSpent.company      14999 non-null  int64
 5   workAccident           14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotionInLast5years  14999 non-null  int64
 8   dept                   14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [32]:
#nummber of rows and number of columns
data.shape

(14999, 10)